version: '3.8'
services:
    php-apache:
        container_name: vsnippet-xss-ethical-hackers-day
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 1337:80
